// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMdHfi5E-5eWmEYti3zEEyJ4e3Di6lHCI',
    appId: '1:649887878541:web:f59a0adf2861a33739c1c4',
    messagingSenderId: '649887878541',
    projectId: 'sentry-bo-v1',
    authDomain: 'sentry-bo-v1.firebaseapp.com',
    storageBucket: 'sentry-bo-v1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOOw2Tjp7TjnUYPLg3ST4yBFEVaFGZVrg',
    appId: '1:649887878541:android:66c58deb99e1a39239c1c4',
    messagingSenderId: '649887878541',
    projectId: 'sentry-bo-v1',
    storageBucket: 'sentry-bo-v1.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMdHfi5E-5eWmEYti3zEEyJ4e3Di6lHCI',
    appId: '1:649887878541:web:179e7cd63198fe7f39c1c4',
    messagingSenderId: '649887878541',
    projectId: 'sentry-bo-v1',
    authDomain: 'sentry-bo-v1.firebaseapp.com',
    storageBucket: 'sentry-bo-v1.firebasestorage.app',
  );
}
